services:
    # Menu Builder
    sandbox_front.menu_builder:
        class: Sandbox\FrontBundle\Menu\Builder
        arguments:
            - @knp_menu.factory
            - @doctrine.orm.entity_manager
            - @security.context
            - @event_dispatcher
            - @bigfoot_navigation.manager.menu_item_url

    # Menu Factory
    sandbox_front.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: sandbox_front.menu_builder
        factory_method: createMainMenu
        scope: request
        arguments:
            - @request
        tags:
            - { name: knp_menu.menu, alias: main_sandbox }