script:
  - composer install -n
  - app/console doctrine:database:create
  - app/console doctrine:schema:update --force
  - app/console doctrine:fixtures:load
  - app/console assetic:dump --env=prod
  - app/console assetic:dump --env=admin