script:
  - composer install -n
  - app/console doctrine:database:create
  - app/console doctrine:schema:update --force
  - app/console doctrine:fixtures:load
#  - setfacl -R -m u:www-data:rwx -m u:`whoami`:rwx app/cache/
#  - setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx app/cache/
#  - setfacl -R -m u:www-data:rwx -m u:`whoami`:rwx app/logs/
#  - setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx app/logs/
  - chmod 777 app/cache app/logs web/uploads
  - app/console assetic:dump --env=prod
  - app/console assetic:dump --env=admin