script:
  - composer install -n
  - app/console doctrine:database:create
  - app/console doctrine:schema:update --force
  - app/console doctrine:fixtures:load
#  - setfacl -R -m u:www-data:rwx -m u:`whoami`:rwx app/cache/
#  - setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx app/cache/
#  - setfacl -R -m u:www-data:rwx -m u:`whoami`:rwx app/logs/
#  - setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx app/logs/
  - sudo chmod +a "www-data allow delete,write,append,file_inherit,directory_inherit" app/cache app/logs
  - sudo chmod +a "`whoami` allow delete,write,append,file_inherit,directory_inherit" app/cache app/logs
  - app/console assetic:dump --env=prod
  - app/console assetic:dump --env=admin