bigfoot_core:
    mailer:
        from: bigfoot@c2is.fr
    languages:
        front:
            fr:
                label:  "French"
                value:  "fr"
                parameters:
                    default_country:    "FR"
                    fullLocale:         "fr_FR"
            en:
                label:  "English"
                value:  "en"
                parameters:
                    default_country:    "GB"
                    fullLocale:         "en_GB"
            de:
                label:  "German"
                value:  "de"
                parameters:
                    default_country:    "DE"
                    fullLocale:         "de_DE"
            es:
                label:  "Spanish"
                value:  "es"
                parameters:
                    default_country:    "ES"
                    fullLocale:         "es_ES"
            it:
                label:  "Italian"
                value:  "it"
                parameters:
                    default_country:    "IT"
                    fullLocale:         "it_IT"
            nl:
                label:  "Netherland"
                value:  "nl"
                parameters:
                    default_country:    "NL"
                    fullLocale:         "nl_NL"

bigfoot_context:
    entities:
        - "Bigfoot\\"
    contexts:
        language:
            loaders:
                back: "bigfoot_language_loader"
            values:
                fr:
                    label: "French"
                    value: "fr"
                en:
                    label: "English"
                    value: "en"
            default_value: %locale%
            label: "Language"

bigfoot_content:
    templates:
        page:
            title_desc:
                class: 'Bigfoot\Bundle\ContentBundle\Entity\Page\TitleDesc'
                sub_templates: ['title_desc_1']
            title_desc_sidebar:
                class: 'Bigfoot\Bundle\ContentBundle\Entity\Page\TitleDescSidebar'
                sub_templates: ['title_desc_sidebar_1', 'title_desc_sidebar_2']
            title_desc_img_sidebar:
                class: 'Bigfoot\Bundle\ContentBundle\Entity\Page\TitleDescImgSidebar'
                sub_templates: ['title_desc_img_sidebar_1']
        sidebar:
            title_block:
                class: 'Bigfoot\Bundle\ContentBundle\Entity\Sidebar\TitleBlock'
                sub_templates: ['title_block_1']
            title_desc_block:
                class: 'Bigfoot\Bundle\ContentBundle\Entity\Sidebar\TitleDescBlock'
                sub_templates: ['title_desc_block_1']
            title_desc_img_block:
                class: 'Bigfoot\Bundle\ContentBundle\Entity\Sidebar\TitleDescImgBlock'
                sub_templates: ['title_desc_img_block_1']
        block:
            title_desc_img:
                class: 'Bigfoot\Bundle\ContentBundle\Entity\Block\TitleDescImg'
                sub_templates: ['title_desc_img_1', 'title_desc_img_2', 'title_desc_img_3']

bigfoot_user:
    resetting:
        token_ttl: 1800

bigfoot_seo:
    default:
        meta_title: "My super duper website of d00m"