imports:
    - { resource: config.yml }
    - { resource: menu_security.yml }

assetic:
    write_to: %kernel.root_dir%/../web/
    bundles: [ BigfootContentBundle, %bigfoot.theme.bundle% ]

twig:
    form:
        resources:
            - '%bigfoot.theme.bundle%:form_custom:inline.html.twig'
    globals:
        theme:         @bigfoot.theme
        bigfoot_theme: %bigfoot_theme%

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_admin.yml"

knp_menu:
    twig:
        template: %bigfoot.theme.bundle%:admin:menu.html.twig

knp_paginator:
    template:
        pagination: %bigfoot.theme.bundle%:admin:sliding.html.twig
