imports:
    - { resource: config.yml }
    - { resource: menu_security.yml }

assetic:
    write_to: %kernel.root_dir%/../web/
    bundles: [ BigfootContentBundle, %bigfoot.theme.bundle% ]

twig:
    form:
        resources:
            - '%bigfoot.theme.bundle%:admin:form_custom_layout.html.twig'
    globals:
        bigfoot_theme_values: %bigfoot.theme.values%
        bigfoot_theme_bundle: %bigfoot.theme.bundle%
        theme: @bigfoot.theme

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_admin.yml"

knp_menu:
    twig:
        template: %bigfoot.theme.bundle%:admin:menu.html.twig

knp_paginator:
    template:
        pagination: %bigfoot.theme.bundle%:admin:sliding.html.twig
