imports:
    - { resource: common.yml }

framework:
    #esi:             ~
    router:
        resource: "%kernel.root_dir%/config/routing.yml"

bigfoot_seo:
    default:
        meta_title: "My super duper website of d00m"
