imports:
    - { resource: common.yml }
    - { resource: security.yml }
    - { resource: menu_security.yml }

assetic:
    bundles: [ %bigfoot.theme.bundle% ]

twig:
    form:
        resources:
            - 'BigfootCoreBundle:form:form_custom_layout.html.twig'
    globals:
        bigfoot_theme_values: %bigfoot.theme.values%
        bigfoot_theme_bundle: %bigfoot.theme.bundle%
        theme: @bigfoot.theme

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_admin.yml"
